import type { Rng } from '../engine/roll.ts';
import type { Attack } from '../combat/types.ts';
import { chainedBook, CHAIN_LENGTH, provableChain, skillBook, volumeFloor } from '../skills/book.ts';
import type { Item } from './types.ts';

/**
 * What the tower gives up.
 *
 * Loot is generated by code from depth, not asked for from the model — the same
 * reason encounters are. Difficulty and reward are the progression curve, and a
 * model inventing a sword per fight would flatten it within a floor.
 *
 * Names stay plain here. Flavour is the Writer's job; this decides the numbers.
 */

/** The supply a short rest burns. Deliberately one well-known id. */
export const RATION_ID = 'rations';

/**
 * How deep the tower is willing to promise it goes.
 *
 * Mirrors `TOWER_HORIZON` in the Signet book. Kept here rather than imported to
 * avoid a cycle, and pinned to it by test.
 */
export const TOWER_DEPTH = 30;

export const rations = (count = 1): { item: Item; count: number } => ({
  item: {
    id: RATION_ID,
    name: 'trail rations',
    description: 'Dry food and clean water — enough to catch your breath on.',
    kind: 'consumable',
    effect: { kind: 'restore', supply: 1 },
    stackable: true,
    value: 5,
  },
  count,
});

/** Healing that scales, so a floor 12 draught is worth carrying. */
export function draught(floor: number): Item {
  const tier = Math.max(1, Math.ceil(Math.max(1, floor) / 5));
  return {
    id: `draught_t${tier}`,
    name: tier === 1 ? 'a clouded phial' : `a clouded phial (${tier})`,
    description: 'Bitter, and it works.',
    kind: 'consumable',
    effect: { kind: 'heal', amount: 4 + tier * 4 },
    stackable: true,
    value: 20 * tier,
    foundOn: floor,
  };
}

const WEAPONS: { name: string; ability: 'str' | 'dex'; range: number; sides: number; hands?: 2 }[] = [
  { name: 'shortsword', ability: 'str', range: 1, sides: 6 },
  // Reach and a shaft need both hands, which is what an off-hand slot is for.
  { name: 'spear', ability: 'str', range: 2, sides: 6, hands: 2 },
  { name: 'axe', ability: 'str', range: 1, sides: 8 },
  { name: 'long knife', ability: 'dex', range: 1, sides: 6 },
  { name: 'sling', ability: 'dex', range: 6, sides: 4 },
];

/** d4 → d6 → d8 → d10 → d12, and no further. */
const DIE_STEPS = [4, 6, 8, 10, 12];

const stepUp = (sides: number, by: number): number => {
  const at = DIE_STEPS.indexOf(sides);
  if (at < 0) return sides;
  return DIE_STEPS[Math.min(DIE_STEPS.length - 1, at + by)];
};

/**
 * A weapon that gets better with the depth it was found at.
 *
 * The improvement steps the damage die rather than adding a flat bonus:
 * `DamageRoll` has no flat term, and widening the combat engine's arithmetic to
 * carry one would ripple through resolve and every test that asserts damage.
 */
export function weapon(rng: Rng, floor: number): Item {
  const base = WEAPONS[Math.floor(rng() * WEAPONS.length)];
  const plus = Math.floor(Math.max(0, floor - 1) / 4);
  const sides = stepUp(base.sides, plus);
  const slug = base.name.replace(/ /g, '');
  const name = plus > 0 ? `${base.name} (d${sides})` : base.name;

  return {
    id: `weapon_${slug}_d${sides}`,
    name,
    description: 'Someone carried this before you did.',
    kind: 'equipment',
    slot: 'main',
    occupies: base.hands === 2 ? ['offhand'] : undefined,
    attack: {
      id: `atk_${slug}_d${sides}`,
      name,
      ability: base.ability,
      proficient: true,
      range: base.range,
      damage: { count: 1, sides, bonusAbility: base.ability, type: 'physical' },
    },
    stackable: false,
    value: 30 + plus * 40,
    foundOn: floor,
  };
}

const ARMOURS = [
  { name: 'padded coat', base: 11 },
  { name: 'ring mail', base: 12 },
  { name: 'scale harness', base: 13 },
];

export function armour(rng: Rng, floor: number): Item {
  const base = ARMOURS[Math.min(ARMOURS.length - 1, Math.floor(rng() * ARMOURS.length) + Math.floor(floor / 10))];
  const plus = Math.floor(Math.max(0, floor - 1) / 6);
  const name = plus > 0 ? `${base.name} +${plus}` : base.name;

  return {
    id: `armour_${base.name.replace(/ /g, '')}_${plus}`,
    name,
    description: 'Battered, and better than nothing.',
    kind: 'equipment',
    slot: 'body',
    armour: base.base + plus,
    stackable: false,
    value: 40 + plus * 50,
    foundOn: floor,
  };
}

/**
 * Signet materials.
 *
 * These do nothing on their own. They exist so a gate can require something
 * that could only have come from a particular depth.
 */
export function material(rng: Rng, floor: number): Item {
  const names = ['a dull shard', 'a knot of wire', 'a sealed vial', 'a chipped sigil'];
  const name = names[Math.floor(rng() * names.length)];
  return {
    id: `mat_${name.replace(/[^a-z]/gi, '')}_${floor}`,
    name,
    description: 'It hums faintly when the light moves.',
    kind: 'material',
    stackable: true,
    value: 10 * Math.max(1, floor),
    foundOn: floor,
  };
}

/**
 * A possession the model named at character creation.
 *
 * Inert by construction. The model is good at "a fisherman's charm, worn
 * smooth" and has no business deciding that it grants +2 to hit — the code
 * grants the kit that has numbers on it.
 */
/**
 * Something you set out holding.
 *
 * `storied` because a keepsake is BY DEFINITION a thing kept for a reason. Most
 * objects roll for a history and most do not get one, which is right — but the
 * things a character owns at the start are the ones that should always have
 * come from somewhere, and it means a new player meets the reading of them
 * rather than meeting an absence.
 */
export const keepsake = (id: string, name: string, description: string): Item => ({
  id: id.trim() || `keepsake_${name.replace(/[^a-z]/gi, '').toLowerCase()}`,
  name,
  description,
  kind: 'material',
  storied: true,
  stackable: false,
  value: 1,
});

export type Drop = { item: Item; count: number };

/**
 * What a won fight yields.
 *
 * Deterministic from the rng the fight already threads, so a replayed log
 * produces the same pack rather than a differently lucky one.
 */
export function rollLoot(rng: Rng, floor: number): Drop[] {
  const drops: Drop[] = [];

  // Something to eat is the common case: rest is a supply economy, and a tower
  // that never yields rations forces a walk home every other fight.
  if (rng() < 0.55) drops.push(rations(1 + Math.floor(rng() * 2)));
  if (rng() < 0.3) drops.push({ item: draught(floor), count: 1 });
  if (rng() < 0.16) drops.push({ item: weapon(rng, floor), count: 1 });
  if (rng() < 0.12) drops.push({ item: armour(rng, floor), count: 1 });
  if (rng() < 0.18) drops.push({ item: material(rng, floor), count: 1 });
  /*
   * Uncommon on purpose: a book is a permanent new verb, not a consumable.
   *
   * Most are standalone; some belong to a series, and a series only drops when
   * the whole of it is reachable in this tower — an unreadable volume three is
   * a dead end the player can never diagnose.
   */
  if (rng() < 0.09) {
    const series = Math.floor(rng() * 6);
    const volume = Math.floor(rng() * CHAIN_LENGTH);
    const chained = rng() < 0.45 && provableChain(series, TOWER_DEPTH) && volumeFloor(series, volume) <= floor;
    drops.push({ item: chained ? chainedBook(rng, series, volume) : skillBook(rng, floor), count: 1 });
  }

  return drops;
}

/** Coin from a won fight, scaled by depth. */
export const rollCoin = (rng: Rng, floor: number): number =>
  Math.floor((2 + rng() * 6) * Math.max(1, floor));

/* -------------------------------------------------------------------------- */
/* Turning what the model named into something you can actually use            */
/* -------------------------------------------------------------------------- */

/**
 * Strip mechanical claims out of a generated description.
 *
 * The model writes "A short, sturdy spear. Range: 1. Damage: 1d6 + Strength
 * modifier. Weight: 3 lbs." — numbers it invented, next to numbers the engine
 * actually holds. When the two disagree the description is simply lying to the
 * player, so the prose keeps the flavour and the item keeps the arithmetic.
 */
export function stripMechanics(description: string): string {
  return description
    .replace(/\b(damage|range|weight|capacity|armou?r class|ac|bonus)\s*:\s*[^.]*\.?/gi, '')
    .replace(/\s{2,}/g, ' ')
    .trim();
}

/**
 * The weapon a character starts holding.
 *
 * Built from the attack the background ALREADY declares, so its numbers are the
 * ones the combat engine was going to use anyway — no name-matching guesswork,
 * and no chance of handing out a sword the model invented the statistics for.
 *
 * `flavour` lets the model's own description survive when it named the same
 * thing in its starting gear, which is where the good prose lives.
 */
export function weaponFromAttack(attack: Attack, flavour?: { name: string; description: string }): Item {
  return {
    id: `weapon_start_${attack.id}`,
    name: flavour?.name ?? attack.name,
    description: flavour ? stripMechanics(flavour.description) : 'Yours, and familiar.',
    kind: 'equipment',
    slot: 'main',
    attack,
    stackable: false,
    value: 25,
    foundOn: 0,
  };
}

/**
 * Whether a named possession is the weapon the background already grants.
 *
 * Matched on a shared significant word, so "Short Spear" in the gear list and a
 * "spear" attack are recognised as the same object rather than issued twice.
 */
export function namesTheSameThing(gearName: string, attackName: string): boolean {
  const words = (text: string) =>
    new Set(text.toLowerCase().split(/[^a-z]+/).filter((w) => w.length > 3));

  const gear = words(gearName);
  for (const word of words(attackName)) if (gear.has(word)) return true;
  return false;
}
