import type { Rng } from '../engine/roll.ts';
import type { Item } from './types.ts';

/**
 * What the tower gives up.
 *
 * Loot is generated by code from depth, not asked for from the model — the same
 * reason encounters are. Difficulty and reward are the progression curve, and a
 * model inventing a sword per fight would flatten it within a floor.
 *
 * Names stay plain here. Flavour is the Writer's job; this decides the numbers.
 */

/** The supply a short rest burns. Deliberately one well-known id. */
export const RATION_ID = 'rations';

export const rations = (count = 1): { item: Item; count: number } => ({
  item: {
    id: RATION_ID,
    name: 'trail rations',
    description: 'Dry food and clean water — enough to catch your breath on.',
    kind: 'consumable',
    effect: { kind: 'restore', supply: 1 },
    stackable: true,
    value: 5,
  },
  count,
});

/** Healing that scales, so a floor 12 draught is worth carrying. */
export function draught(floor: number): Item {
  const tier = Math.max(1, Math.ceil(Math.max(1, floor) / 5));
  return {
    id: `draught_t${tier}`,
    name: tier === 1 ? 'a clouded phial' : `a clouded phial (${tier})`,
    description: 'Bitter, and it works.',
    kind: 'consumable',
    effect: { kind: 'heal', amount: 4 + tier * 4 },
    stackable: true,
    value: 20 * tier,
    foundOn: floor,
  };
}

const WEAPONS: { name: string; ability: 'str' | 'dex'; range: number; sides: number }[] = [
  { name: 'shortsword', ability: 'str', range: 1, sides: 6 },
  { name: 'spear', ability: 'str', range: 2, sides: 6 },
  { name: 'axe', ability: 'str', range: 1, sides: 8 },
  { name: 'long knife', ability: 'dex', range: 1, sides: 6 },
  { name: 'sling', ability: 'dex', range: 6, sides: 4 },
];

/** d4 → d6 → d8 → d10 → d12, and no further. */
const DIE_STEPS = [4, 6, 8, 10, 12];

const stepUp = (sides: number, by: number): number => {
  const at = DIE_STEPS.indexOf(sides);
  if (at < 0) return sides;
  return DIE_STEPS[Math.min(DIE_STEPS.length - 1, at + by)];
};

/**
 * A weapon that gets better with the depth it was found at.
 *
 * The improvement steps the damage die rather than adding a flat bonus:
 * `DamageRoll` has no flat term, and widening the combat engine's arithmetic to
 * carry one would ripple through resolve and every test that asserts damage.
 */
export function weapon(rng: Rng, floor: number): Item {
  const base = WEAPONS[Math.floor(rng() * WEAPONS.length)];
  const plus = Math.floor(Math.max(0, floor - 1) / 4);
  const sides = stepUp(base.sides, plus);
  const slug = base.name.replace(/ /g, '');
  const name = plus > 0 ? `${base.name} (d${sides})` : base.name;

  return {
    id: `weapon_${slug}_d${sides}`,
    name,
    description: 'Someone carried this before you did.',
    kind: 'equipment',
    slot: 'weapon',
    attack: {
      id: `atk_${slug}_d${sides}`,
      name,
      ability: base.ability,
      proficient: true,
      range: base.range,
      damage: { count: 1, sides, bonusAbility: base.ability, type: 'physical' },
    },
    stackable: false,
    value: 30 + plus * 40,
    foundOn: floor,
  };
}

const ARMOURS = [
  { name: 'padded coat', base: 11 },
  { name: 'ring mail', base: 12 },
  { name: 'scale harness', base: 13 },
];

export function armour(rng: Rng, floor: number): Item {
  const base = ARMOURS[Math.min(ARMOURS.length - 1, Math.floor(rng() * ARMOURS.length) + Math.floor(floor / 10))];
  const plus = Math.floor(Math.max(0, floor - 1) / 6);
  const name = plus > 0 ? `${base.name} +${plus}` : base.name;

  return {
    id: `armour_${base.name.replace(/ /g, '')}_${plus}`,
    name,
    description: 'Battered, and better than nothing.',
    kind: 'equipment',
    slot: 'armour',
    armour: base.base + plus,
    stackable: false,
    value: 40 + plus * 50,
    foundOn: floor,
  };
}

/**
 * Signet materials.
 *
 * These do nothing on their own. They exist so a gate can require something
 * that could only have come from a particular depth.
 */
export function material(rng: Rng, floor: number): Item {
  const names = ['a dull shard', 'a knot of wire', 'a sealed vial', 'a chipped sigil'];
  const name = names[Math.floor(rng() * names.length)];
  return {
    id: `mat_${name.replace(/[^a-z]/gi, '')}_${floor}`,
    name,
    description: 'It hums faintly when the light moves.',
    kind: 'material',
    stackable: true,
    value: 10 * Math.max(1, floor),
    foundOn: floor,
  };
}

/**
 * A possession the model named at character creation.
 *
 * Inert by construction. The model is good at "a fisherman's charm, worn
 * smooth" and has no business deciding that it grants +2 to hit — the code
 * grants the kit that has numbers on it.
 */
export const keepsake = (id: string, name: string, description: string): Item => ({
  id: id.trim() || `keepsake_${name.replace(/[^a-z]/gi, '').toLowerCase()}`,
  name,
  description,
  kind: 'material',
  stackable: false,
  value: 1,
});

export type Drop = { item: Item; count: number };

/**
 * What a won fight yields.
 *
 * Deterministic from the rng the fight already threads, so a replayed log
 * produces the same pack rather than a differently lucky one.
 */
export function rollLoot(rng: Rng, floor: number): Drop[] {
  const drops: Drop[] = [];

  // Something to eat is the common case: rest is a supply economy, and a tower
  // that never yields rations forces a walk home every other fight.
  if (rng() < 0.55) drops.push(rations(1 + Math.floor(rng() * 2)));
  if (rng() < 0.3) drops.push({ item: draught(floor), count: 1 });
  if (rng() < 0.16) drops.push({ item: weapon(rng, floor), count: 1 });
  if (rng() < 0.12) drops.push({ item: armour(rng, floor), count: 1 });
  if (rng() < 0.18) drops.push({ item: material(rng, floor), count: 1 });

  return drops;
}

/** Coin from a won fight, scaled by depth. */
export const rollCoin = (rng: Rng, floor: number): number =>
  Math.floor((2 + rng() * 6) * Math.max(1, floor));
