import type { Ability, Abilities } from '../combat/types.ts';
import { mulberry32 } from '../engine/roll.ts';
import type { Rng } from '../engine/roll.ts';
import type { TraitCondition } from './traits.ts';

/**
 * The passive tree.
 *
 * A Path of Exile-shaped skill system: one large graph, entered at a point
 * decided by your background, where a point may only be spent on a node
 * ADJACENT to one you already hold. That contiguity rule is what makes the tree
 * a set of routes rather than a shopping list — reaching a distant keystone
 * means paying for everything on the way, so a build is the path you took.
 *
 * The tree is GENERATED, not authored, and generated by code rather than by the
 * model: it is deterministic from the world seed and the background, so the
 * same character always gets the same tree, a replayed log allocates the same
 * nodes, and no model call is needed to draw it. A node granting whatever a
 * language model felt like would be unbalanceable.
 *
 * It is dynamic in one specific sense: some nodes are HIDDEN behind conditions
 * and do not exist on the map until you have done the thing. That is the seam
 * the Signet system will hang from.
 */

export const NODE_KINDS = ['minor', 'notable', 'keystone'] as const;
export type NodeKind = (typeof NODE_KINDS)[number];

export type NodeGrant = {
  ability?: Partial<Abilities>;
  maxHp?: number;
  ac?: number;
  /** Flat bonus to hit. */
  attack?: number;
  /** Flat bonus to damage. */
  damage?: number;
};

export type SkillNode = {
  id: string;
  name: string;
  description: string;
  kind: NodeKind;
  /** Rings out from the start. Drives both power and layout. */
  ring: number;
  x: number;
  y: number;
  connections: string[];
  grant: NodeGrant;
  /** Keystones give with one hand and take with the other. */
  cost?: NodeGrant;
  /**
   * Hidden until earned.
   *
   * A node with unmet requirements is not drawn at all — the dynamic half of
   * the tree, and where Signet gates will attach.
   */
  requires?: TraitCondition[];
};

export type SkillTree = {
  id: string;
  start: string;
  nodes: SkillNode[];
};

export type Lang = 'th' | 'en';

/* -------------------------------------------------------------------------- */
/* Naming                                                                      */
/* -------------------------------------------------------------------------- */

/**
 * Names come from a word bank rather than a model call.
 *
 * A tree is fifty-odd nodes. Asking a model to name each one would cost a long
 * pause and a lot of tokens every time a character is made, and would not be
 * deterministic. Thai gets Thai words, so a Thai character does not read
 * English node names.
 */
const WORDS = {
  en: {
    str: ['Brawn', 'Heavy Hand', 'Sinew', 'Bulwark'],
    dex: ['Quickness', 'Light Step', 'Deft Hand', 'Reflex'],
    con: ['Hardiness', 'Deep Wind', 'Grit', 'Stamina'],
    int: ['Study', 'Recall', 'Insight', 'Method'],
    wis: ['Watchfulness', 'Patience', 'Instinct', 'Clarity'],
    cha: ['Presence', 'Poise', 'Command', 'Warmth'],
    notable: ['Discipline of the %s', 'Mark of %s', 'The %s Way'],
    keystone: ['Glass Edge', 'Ironclad', 'Duelist Heart', 'Long Vigil'],
  },
  th: {
    str: ['กำลัง', 'มือหนัก', 'เอ็นเหล็ก', 'กำแพง'],
    dex: ['ความไว', 'ย่างเบา', 'มือฉมัง', 'ปฏิกิริยา'],
    con: ['ความทน', 'ลมลึก', 'ความอึด', 'กำลังวังชา'],
    int: ['การศึกษา', 'ความจำ', 'ญาณทัศน์', 'ระเบียบวิธี'],
    wis: ['ความช่างสังเกต', 'ความอดทน', 'สัญชาตญาณ', 'ความกระจ่าง'],
    cha: ['บารมี', 'ความสง่า', 'อำนาจสั่งการ', 'ไมตรี'],
    notable: ['วินัยแห่ง%s', 'รอยแห่ง%s', 'วิถี%s'],
    keystone: ['คมกระจก', 'เกราะเหล็ก', 'ใจนักดวล', 'เฝ้ายาม'],
  },
} as const;

type WordBank = (typeof WORDS)['en'] | (typeof WORDS)['th'];

const pick = <T,>(rng: Rng, list: readonly T[]): T => list[Math.floor(rng() * list.length)];

/* -------------------------------------------------------------------------- */
/* Generation                                                                  */
/* -------------------------------------------------------------------------- */

const ABILITY_LIST: Ability[] = ['str', 'dex', 'con', 'int', 'wis', 'cha'];

/** A stable number from a string, so the same background always seeds the same. */
function hash(text: string): number {
  let h = 2166136261;
  for (let i = 0; i < text.length; i++) {
    h ^= text.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

export const RINGS = 4;
/** Routes radiating from the centre. */
export const BRANCHES = 6;

const KEYSTONES: { grant: NodeGrant; cost: NodeGrant; note: Record<Lang, string> }[] = [
  {
    grant: { damage: 2, attack: 1 },
    cost: { maxHp: 6 },
    note: { en: 'You hit far harder, and you break far sooner.', th: 'ตีหนักขึ้นมาก แต่ก็ล้มง่ายขึ้นมาก' },
  },
  {
    grant: { ac: 2, maxHp: 6 },
    cost: { attack: 1 },
    note: { en: 'Nothing gets through you. Nothing much gets past you either.', th: 'ไม่มีอะไรผ่านคุณไปได้ และคุณก็ไล่ตามใครแทบไม่ทัน' },
  },
  {
    grant: { attack: 2 },
    cost: { ac: 1 },
    note: { en: 'You fight forward, and take whatever comes with it.', th: 'คุณบุกไปข้างหน้า และรับทุกอย่างที่ตามมา' },
  },
  {
    grant: { maxHp: 10 },
    cost: { damage: 1 },
    note: { en: 'You outlast. You do not overwhelm.', th: 'คุณอยู่ได้นานกว่า แต่ไม่ได้ชนะเร็วกว่า' },
  },
];

/**
 * Build the tree.
 *
 * Six routes, four rings deep: a chain of minors out to a notable, with a
 * keystone on the rim. Deterministic in the seed and the background, so it is
 * never stored — it is regenerated identically wherever it is needed.
 */
export function skillTreeFor(seed: number, backgroundId: string, language: Lang = 'en'): SkillTree {
  const rng = mulberry32((seed ^ hash(backgroundId)) >>> 0);
  const words: WordBank = WORDS[language];
  const nodes: SkillNode[] = [];

  const start: SkillNode = {
    id: 'start',
    name: language === 'th' ? 'จุดเริ่ม' : 'Origin',
    description: language === 'th' ? 'จุดที่ทุกอย่างเริ่มต้น' : 'Where everything starts.',
    kind: 'minor',
    ring: 0,
    x: 50,
    y: 50,
    connections: [],
    grant: {},
  };
  nodes.push(start);

  for (let branch = 0; branch < BRANCHES; branch++) {
    // Each route leans on one ability, which is what gives it an identity.
    const ability = ABILITY_LIST[(branch + Math.floor(rng() * ABILITY_LIST.length)) % ABILITY_LIST.length];
    const angle = (branch / BRANCHES) * Math.PI * 2 + rng() * 0.25;
    let previous = start.id;

    for (let ring = 1; ring <= RINGS; ring++) {
      const radius = ring * 11;
      const wobble = (rng() - 0.5) * 0.18;
      const id = `b${branch}r${ring}`;
      const isKeystone = ring === RINGS;
      const isNotable = ring === RINGS - 1;
      const kind: NodeKind = isKeystone ? 'keystone' : isNotable ? 'notable' : 'minor';

      const node: SkillNode = {
        id,
        name: nameFor(rng, words, ability, kind),
        description: '',
        kind,
        ring,
        x: 50 + Math.cos(angle + wobble) * radius,
        y: 50 + Math.sin(angle + wobble) * radius,
        connections: [previous],
        grant: {},
      };

      if (kind === 'minor') {
        node.grant = rng() < 0.6 ? { ability: { [ability]: 1 } } : { maxHp: 3 };
      } else if (kind === 'notable') {
        node.grant = { ability: { [ability]: 1 }, ...(rng() < 0.5 ? { attack: 1 } : { ac: 1 }) };
      } else {
        // A keystone is a trade, not an upgrade. Without the cost, every build
        // converges on taking all of them.
        const trade = pick(rng, KEYSTONES);
        node.grant = trade.grant;
        node.cost = trade.cost;
        node.description = trade.note[language];
        // The rim is where the tree grows: these appear only once earned.
        node.requires = [{ kind: 'level', atLeast: 4 + branch }];
      }

      if (!node.description) node.description = describe(node.grant, node.cost, language);
      nodes.push(node);
      previous = id;
    }
  }

  // Cross-links, so routes join up and the tree is a graph rather than six
  // separate ladders — the point of contiguity is that paths can meet.
  for (let branch = 0; branch < BRANCHES; branch++) {
    const here = `b${branch}r2`;
    const next = `b${(branch + 1) % BRANCHES}r2`;
    const node = nodes.find((n) => n.id === here);
    if (node && rng() < 0.5) node.connections.push(next);
  }

  return { id: `tree_${backgroundId}`, start: start.id, nodes: linkBothWays(nodes) };
}

function nameFor(rng: Rng, words: WordBank, ability: Ability, kind: NodeKind): string {
  if (kind === 'keystone') return pick(rng, words.keystone);
  const base = pick(rng, words[ability]);
  if (kind === 'notable') return pick(rng, words.notable).replace('%s', base);
  return base;
}

function describe(grant: NodeGrant, cost: NodeGrant | undefined, language: Lang): string {
  const parts: string[] = [];
  for (const [ability, bonus] of Object.entries(grant.ability ?? {})) parts.push(`+${bonus} ${ability}`);
  if (grant.maxHp) parts.push(`+${grant.maxHp} hp`);
  if (grant.ac) parts.push(`+${grant.ac} armour`);
  if (grant.attack) parts.push(`+${grant.attack} to hit`);
  if (grant.damage) parts.push(`+${grant.damage} damage`);
  for (const [ability, penalty] of Object.entries(cost?.ability ?? {})) parts.push(`-${penalty} ${ability}`);
  if (cost?.maxHp) parts.push(`-${cost.maxHp} hp`);
  if (cost?.ac) parts.push(`-${cost.ac} armour`);
  if (cost?.attack) parts.push(`-${cost.attack} to hit`);
  if (cost?.damage) parts.push(`-${cost.damage} damage`);
  return parts.join(', ') || (language === 'th' ? 'ทางผ่าน' : 'a step along the way');
}

/** Edges are undirected; the generator writes only one side. */
function linkBothWays(nodes: SkillNode[]): SkillNode[] {
  const byId = new Map(nodes.map((n) => [n.id, { ...n, connections: [...n.connections] }]));
  for (const node of nodes) {
    for (const to of node.connections) {
      const other = byId.get(to);
      if (other && !other.connections.includes(node.id)) other.connections.push(node.id);
    }
  }
  return [...byId.values()];
}
